### ISSUE TITLE
LoRaServer docker ports

### ISSUE THREAD

**Issue by iakrevetkho** [brocaar/loraserver-docker#7]
In _docker-compose.yml_ you should configure port of _loraserver_ like:
```
loraserver:
    image: loraserver/loraserver:2
    ports:
     - 8000:8000
    volumes:
      - ./configuration/loraserver:/etc/loraserver
```

Otherwise, lora_app_server cannot connect to it.
